### ISSUE TITLE
Support GitHub - the first iteration

### ISSUE THREAD

**Issue by nhat-phan** [nhat-phan/merge-request-integration#26]
**Documentation**: https://developer.github.com/v3/
**Github client**: https://github.com/github-api/github-api

**Acceptance Criteria**:

- [ ] Can config an connection to GitHub
- [ ] Can see the list of pull requests assigned to logged in user/wait for logged in user to review
- [ ] Can filter the pull requests by status (merged/opened/closed)
- [ ] Can see commits
- [ ] Can see comments
- [ ] Can leave a comment in a specific position
- [ ] Can delete a comment

**Nice to have**:

- [ ] Filter by assigner/reviewer
- [ ] Pipeline status
- [ ] Can resolve a comment

**Tasks**:

- [x] Configuration page
- [x] Implement User Api
- [x] Implement Project Api - for github it’s Repository api
- [ ] Implement Merge Request Api - for github it’s Pull Request
- [ ] Implement Comment Api
- [ ] Manual testing

**Notes/difficulties/questions**:

1. How to get members of the repository?
2. How to get pipeline status of the pull request? Required information:
- Latest pipeline status: running/passed/failed
- Web url of latest pipeline
3. Should the throttle limit be displayed somewhere? if yes how to log the request by time effectively?
4. Is there any self-signed certificate concern for custom GitHub server?

**Comment by nhat-phan** [comment]
Intellij supports a bundled Github plugin which have a comment functionality review since 2020.1 EAP version. So I'll focus on improving the plugin functionality before porting to Github.
